import { CreditCard } from '@/types/creditCard';

export const mockCards: CreditCard[] = [
  {
    id: '1',
    bankName: 'ICICI Bank',
    cardName: 'Coral',
    billingDate: 2,
    currentBill: 8115,
    status: 'active',
    limitType: 'monthly',
    limitAmount: 25000,
    notes: 'Only ICICI card with a bill this month',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    bankName: 'ICICI Bank',
    cardName: 'Amazon Pay',
    billingDate: 2,
    currentBill: 0,
    status: 'active',
    limitType: 'per-transaction',
    limitAmount: 10000,
    notes: 'No bill this month',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    bankName: 'HDFC Bank',
    cardName: 'Tata Neu',
    billingDate: 1,
    currentBill: 0,
    status: 'active',
    limitType: 'monthly',
    limitAmount: 15000,
    notes: 'No bill this month',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    bankName: 'HDFC Bank',
    cardName: 'Swiggy',
    billingDate: 15,
    currentBill: 1100.3,
    status: 'active',
    limitType: 'per-transaction',
    limitAmount: 5000,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    bankName: 'HDFC Bank',
    cardName: 'Flipkart',
    billingDate: 1,
    currentBill: 0,
    status: 'active',
    limitType: 'monthly',
    limitAmount: 20000,
    notes: 'No bill this month',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    bankName: 'Axis Bank',
    cardName: 'My Zone',
    billingDate: 1,
    currentBill: 0,
    status: 'active',
    limitType: 'per-transaction',
    limitAmount: 8000,
    notes: 'No bill this month',
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    bankName: 'BharatPe',
    cardName: 'Credit Card',
    billingDate: 15,
    currentBill: 0,
    status: 'blocked',
    limitType: 'full-card',
    limitAmount: 40000,
    notes: 'Cannot access app due to account block',
    createdAt: new Date().toISOString(),
  },
];
